# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # run tests!
      - run: yarn lint

      # run build!
      - run: yarn build

      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "0b:03:90:e7:06:6c:a6:45:d7:76:bc:9d:d3:94:af:cb"

      deployment:
          staging:
            branch: test-ci
            heroku:
              appname: vavdav-testci
